apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: cast-db
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          value: "cast_db_username"
        - name: POSTGRES_PASSWORD
          value: "cast_db_password"
        - name: POSTGRES_DB
          value: "cast_db_dev"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-data-cast-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  namespace: movie-app
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: cast-db
