apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
