apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.nodePort }}
  selector:
    app: nginx
