apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: movie-db
